### ISSUE TITLE
Occasional game not loading on iPhone

### ISSUE THREAD

**Issue by kirakira** [kirakira/zaixianxiangqi#4]
Happened several times on Zhaoyeye's phone. Not easily reproducible. Need more information to debug.

**Comment by jyoung913** [comment]
Maybe Zhaoyeye sabi is the cause?

**Comment by kirakira** [comment]
This was caused by a bug in Safari's handling of defer attribute. Fixed in e97bcae984a81c004440b315e015757bae9e17d5.
